quanlysv/config/routes.rb
Rails.application.routes.draw do
  get "login" => 'session#new'
  post "login" => 'session#create'
  get "logout" => 'session#destroy'
  get "welcome" => 'home#top'
  resources :ql_tvs
  resources :session

    get 'home/top'
    get 'home/about'
    get 'ql_tvs/index'
    get 'home/personal'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "ql_tvs#index"
  # root "articles#index"
end

quanlysv/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

quanlysv/app/models/ql_tv.rb
class QlTv < ApplicationRecord
    validates :sv_id, uniqueness: true, allow_blank: false

end

quanlysv/app/models/scaffold.rb
class Scaffold < ApplicationRecord
end

quanlysv/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionHelper
    helper_method :current_user
    helper_method :logged_in?
    add_flash_types :info, :error, :success
    def current_user
       QlTv.find_by(sv_id: session[:sv_id])
    end
    def logged_in?
        !current_user.nil?
    end
end

quanlysv/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

quanlysv/app/controllers/ql_tvs_controller.rb
class QlTvsController < ApplicationController
  before_action :set_ql_tv, only: %i[ show edit update destroy ]

  # GET /ql_tvs or /ql_tvs.json
  def index
    @ql_tvs = QlTv.all
  end

  # GET /ql_tvs/1 or /ql_tvs/1.json
  def show
  end

  # GET /ql_tvs/new
  def new
    @ql_tv = QlTv.new
  end

  # GET /ql_tvs/1/edit
  def edit
  end

  # POST /ql_tvs or /ql_tvs.json
  def create
    @ql_tv = QlTv.new(ql_tv_params)

    respond_to do |format|
      if @ql_tv.save
        flash.now[:notice] = "We have exactly"
        format.html { redirect_to ql_tv_url(@ql_tv), notice: "Tạo mới cây thành công." }
        format.json { render :show, status: :created, location: @ql_tv }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ql_tv.errors, status: :unprocessable_entity }
      end 
    end
  end

  # PATCH/PUT /ql_tvs/1 or /ql_tvs/1.json
  def update
    respond_to do |format|
      if @ql_tv.update(ql_tv_params)
        format.html { redirect_to ql_tv_url(@ql_tv), notice: "Cập nhật cây thành công." }
        format.json { render :show, status: :ok, location: @ql_tv }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ql_tv.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ql_tvs/1 or /ql_tvs/1.json
  def destroy
    @ql_tv.destroy

    respond_to do |format|
      format.html { redirect_to ql_tvs_url, notice: "Xóa Cây thành công." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ql_tv
      @ql_tv = QlTv.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ql_tv_params
      params.require(:ql_tv).permit(:sv_id, :sv_name, :sv_class, :sv_addr, :sv_dob,:sv_duoctinh,:sv_note,:sv_place)
    end
end

quanlysv/app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = QlTv.find_by sv_id: params[:session][:id]
    if (user && user.authenticate(params[:session][:password]))
      log_in user
      redirect_to '/welcome'
      flash[:notice] = "Đăng nhập thành công"
    else
      flash[:notice] = "Mã sinh viên hoặc mật khẩu không đúng"
      render :new
    end
  end

  def destroy
    session[:sv_id] = nil
    redirect_to root_path, notice: "Đã đăng xuất"
  end
end

quanlysv/app/helpers/application_helper.rb
module ApplicationHelper
end

quanlysv/app/helpers/home_helper.rb
module HomeHelper
end

quanlysv/app/helpers/ql_tvs_helper.rb
module QlTvsHelper
end

quanlysv/app/helpers/session_helper.rb
module SessionHelper
    def log_in user
        session[:sv_id] = user.sv_id
    end

    def log_out
    session.delete :sv_id
  end
end

quanlysv/app/views/home/_footer.html.erb
<!-- Footer -->
<header class="text-center text-lg-start bg-white text-muted">
    <!-- Section: Social media -->
    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
        <!-- Left -->
        <div class="me-5 d-none d-lg-block">
            <span>Get connected with us on social networks:</span>
        </div>
        <!-- Left -->

        <!-- Right -->
        <div>
            <a href="" class="me-4 link-secondary">
                <i class="fab fa-facebook-f"></i>
            </a>
            <a href="" class="me-4 link-secondary">
                <i class="fab fa-twitter"></i>
            </a>
            <a href="" class="me-4 link-secondary">
                <i class="fab fa-google"></i>
            </a>
            <a href="" class="me-4 link-secondary">
                <i class="fab fa-instagram"></i>
            </a>
            <a href="" class="me-4 link-secondary">
                <i class="fab fa-linkedin"></i>
            </a>
            <a href="" class="me-4 link-secondary">
                <i class="fab fa-github"></i>
            </a>
        </div>
        <!-- Right -->
    </section>
    <!-- Section: Social media -->

    <!-- Section: Links  -->
    <section class="">
        <div class="container text-center text-md-start mt-5">
            <!-- Grid row -->
            <div class="row mt-3">
                <!-- Grid column -->
                <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                    <!-- Content -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        <i class="fas fa-gem me-3 text-secondary"></i>Company name
                    </h6>
                    <p>
                        Here you can use rows and columns to organize your footer content. Lorem ipsum
                        dolor sit amet, consectetur adipisicing elit.
                    </p>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        Products
                    </h6>
                    <p>
                        <a href="#!" class="text-reset">Angular</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">React</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Vue</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Laravel</a>
                    </p>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        Useful links
                    </h6>
                    <p>
                        <a href="#!" class="text-reset">Pricing</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Settings</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Orders</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Help</a>
                    </p>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
                    <p><i class="fas fa-home me-3 text-secondary"></i> New York, NY 10012, US</p>
                    <p>
                        <i class="fas fa-envelope me-3 text-secondary"></i>
                        info@example.com
                    </p>
                    <p><i class="fas fa-phone me-3 text-secondary"></i> + 01 234 567 88</p>
                    <p><i class="fas fa-print me-3 text-secondary"></i> + 01 234 567 89</p>
                </div>
                <!-- Grid column -->
            </div>
            <!-- Grid row -->
        </div>
    </section>
    <!-- Section: Links  -->

    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.025);">
        © 2021 Copyright:
        <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
    </div>
    <!-- Copyright -->
</header>
<!-- Footer --> 

quanlysv/app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to 'VuDung Site' ,ql_tvs_path, class:"navbar-brand" %>
    <!-- <a class="navbar-brand" href="#">VUDUNG WEBSITE</a> -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                 <%= link_to 'Trang quản lý' ,ql_tvs_path, class:"nav-link" %>
                <!-- <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a> -->
            </li>
           
        </ul>

    </div>
</nav>

quanlysv/app/views/home/about.html.erb
<h1>Xin Chao, Day la Vu Dung</h1>

<div class="container">

    <ul>
        <li>MSV: 1911505310109</li>
        <li>Hoten: Nguyen Vu Dung</li>
        <li>Lop: 19T1</li>
        <li>Address: Da Nang</li>
        
    </ul>

</div>

quanlysv/app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Trang Chủ</p>

quanlysv/app/views/home/login.html.erb
<div class="login">
<h2 class="label_login">Đăng Nhập</h2>    
<form>
  <!-- Email input -->
  <div class="form-outline mb-4">
    <input type="email" id="form2Example1" class="form-control" />
    <label class="form-label" for="form2Example1">Mã sinh viên</label>
  </div>

  <!-- Password input -->
  <div class="form-outline mb-4">
    <input type="password" id="form2Example2" class="form-control" />
    <label class="form-label" for="form2Example2">Mật khẩu</label>
  </div>

  <!-- 2 column grid layout for inline styling -->
  <div class="row mb-4">
    <div class="col d-flex justify-content-center">
      <!-- Checkbox -->
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="form2Example31" checked />
        <label class="form-check-label" for="form2Example31"> Remember me </label>
      </div>
    </div>

    <div class="col">
      <!-- Simple link -->
      <a href="#!">Forgot password?</a>
    </div>
  </div>

  <!-- Submit button -->
  <button type="button" class="btn btn-primary btn-block mb-4">Đăng nhập</button>

  <!-- Register buttons -->
  <div class="text-center">
    <a href="#!"><%= link_to "Đăng ký tài khoản mới" , new_ql_tv_path %>
</a></p>
  </div>
</form>
</div>

quanlysv/app/views/home/personal.html.erb
<div class="container">
    <h1>Xin chào bạn</h1>
    <h4>Bạn chưa đăng nhập,<%= link_to " mời bạn đăng nhập", login_path%></h4>
</div>

quanlysv/app/views/home/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-offset-3 col-lg-6">
      <div class="text-left">
        <h1>Trang chủ</h1>
        <% if logged_in? %>
          <p style="color: green"><%= notice %></p>
          <h2>Xin Chào, <%= current_user.sv_name %></h2>
           <%= link_to "Đăng xuất", logout_path, method: :delete %> 
           <% else  %>
            <%= link_to "Mời bạn login", login_path%>
        <% end %>
      </div>
    </div>
  </div>
</div>

quanlysv/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppDemo1</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>  

    <style>
      #footer {
        position:absolute;
        bottom:0;
        width:100%;
        height:60px;   /* Height of the footer */
        background:#6cf;
      }

    </style>
  </head>

  <body>

    <%= render 'home/header' %>
  
    <div class="container">
      <%= yield %>
      <br>
    </div>



    <%= render 'home/footer' %>
    
    
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
  </body>
</html>

quanlysv/app/views/ql_tvs/_form.html.erb
<%= form_with(model: ql_tv) do |form| %>
  <% if ql_tv.errors.any? %>
    <div style="color: red">
      <h4><%= pluralize(ql_tv.errors.count, "error") %></h4>
      <ul>
        <% ql_tv.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <label for="exampleInputEmail1">Mã cây</label>
    <%# <%= form.label :sv_id, style: "display: block" %>
    <%= form.text_field :sv_id, class:"form-control", placeholder: "Nhập mã sinh viên", style:"width:290px",required:'required' %>
  </div>

  <div>
    <label for="exampleInputEmail1">Tên Cây</label>
    <%# <%= form.label :sv_id, style: "display: block" %>
    <%= form.text_field :sv_name, class:"form-control",placeholder: "Nhập họ và tên", style:"width:290px",required:'required' %>
  </div>

  <div>
    <label for="exampleInputEmail1">Đặc điểm</label>
    <%# <%= form.label :sv_id, style: "display: block" %>
    <%= form.text_field :sv_class, class:"form-control",placeholder: "Nhập lớp sinh hoạt", style:"width:290px",required:'required' %>
  </div>

  <div>
    <label for="exampleInputEmail1">Nơi trồng</label>
    <%# <%= form.label :sv_id, style: "display: block" %>
    <%= form.text_field :sv_addr, class:"form-control",placeholder: "Nhập địa chỉ", style:"width:290px",required:'required' %>
  </div>
  <div>
    <label for="exampleInputEmail1">Ngày nhập</label>
    <%# <%= form.label :sv_dob, style: "display: block" %>
    <%= form.date_field :sv_dob,class:"form-control",placeholder:"Chọn ngày nhập hàng",style:"width:290px",required:'required' %>
  </div>
  <div>
    <label for="exampleInputEmail1">Dược tính</label>
    <%# <%= form.label :sv_dob, style: "display: block" %>
    <%= form.text_field :sv_duoctinh,class:"form-control",placeholder:"Điền dược tính",style:"width:290px",required:'required' %>
  </div>
  <div>
    <label for="exampleInputEmail1">Lưu ý</label>
    <%# <%= form.label :sv_dob, style: "display: block" %>
    <%= form.text_field :sv_note,class:"form-control",placeholder:"Điền lưu ý sử dụng",style:"width:290px",required:'required' %>
  </div>
  <div>
    <label for="exampleInputEmail1">Màu lá</label>
    <%# <%= form.label :sv_dob, style: "display: block" %>
    <%= form.text_field :sv_place,class:"form-control",placeholder:"Điền màu lá",style:"width:290px",required:'required' %>
  </div>
  <div>
    <br>
      <%= if request.url.include? "edit" 
            form.submit "Cập nhật", class:"btn btn-primary"
          else
            form.submit "Tạo mới", class:"btn btn-primary"
          end %>
  </div>
<% end %>

quanlysv/app/views/ql_tvs/_ql_tv.html.erb
<div id="<%= dom_id ql_tv %>">
  <td>
    <%= ql_tv.sv_id %>
  </td>
  
  <td>
    <%= ql_tv.sv_name %>
  </td>

  <td>
    <%= ql_tv.sv_class %>
  </td>

  <td>
    <%= ql_tv.sv_addr %>
  </td>

  <td>
    <%= ql_tv.sv_dob.strftime('%d-%m-%Y')  %>
    </td>
  <td>
    <%= ql_tv.sv_duoctinh  %>
    </td>
  <td>
    <%= ql_tv.sv_note  %>
    </td>

   <td>
    <%= ql_tv.sv_place  %>
    </td> 
  <%# <td>
    <%= ql_tv.password_digest %>
  <%# </td>  %>
  <td><%= link_to "Xem chi tiết", ql_tv %></td>
</div>

quanlysv/app/views/ql_tvs/edit.html.erb
<h1>Chỉnh sửa thông tin cây thuốc</h1>

<%= render "form", ql_tv: @ql_tv %>

<br>

<div>
  <%# <%= link_to "Show this ql tv", @ql_tv %> 
  <%= link_to "Quay lại quản lý cây thuốc", ql_tvs_path %>
</div>

quanlysv/app/views/ql_tvs/index.html.erb
<div class="container">
    <div class="title-school" style="width: 410px;">
    <p class="lead"
        style="text-align: center ; font-weight: bold; font-family: 'Times New Roman', Times, serif; color: rgb(50, 205, 68);">
        ĐẠI HỌC ĐÀ NÃNG</p>
    <p class="lead"
        style="margin-top: -20px;text-align: center ; font-weight: bold; font-family: 'Times New Roman', Times, serif; color: rgb(50, 205, 68);">
        TRƯỜNG ĐẠI HỌC SƯ PHẠM KỸ THUẬT
    </p>
    </div>
    <p
        style="text-align: center; font-weight: bold; font-family: 'Times New Roman', Times, serif; font-size: 30px; color: red;">
        <%= image_tag "open-book.png" %> QUẢN LÝ CÂY THUỐC
    </p>
</div>
<table class="table table-striped" style="width: 110%">
  <thead>
    <tr>
      <th scope="col-md-auto">STT</th>
      <th scope="col-md-auto">Mã Cây</th>
      <th scope="col-md-auto">Tên Cây</th>
      <th scope="col-md-auto">Đặc điểm</th>
      <th scope="col-md-auto">Nơi trồng</th>
      <th scope="col-md-auto">Ngày nhập</th>
      <th scope="col-md-auto">Dược tính</th>
      <th scope="col-md-auto">Lưu ý</th>
      <th scope="col-md-auto">Màu lá</th>
      <th scope="col-md-auto"></th>
    </tr>
  </thead>
  <tbody>
    <div id="ql_tvs">
      <% i=0 %>
      <% @ql_tvs.each do |ql_tv| i=i+1 %> 
      <tr>
      <td><%= i %></td>
      <%= render ql_tv %>
      </tr>
      <!-- <p><%= link_to "Show this ql tv", ql_tv %></p> -->
      <% end %>
    </div>
  </tbody>
</table>

<%= link_to "Nhập cây mới" , new_ql_tv_path, class:"btn btn-primary" %>

quanlysv/app/views/ql_tvs/new.html.erb
<h1>Nhập mới cây thuốc</h1>

<%= render "form", ql_tv: @ql_tv %>

<br>

<div>
  <%= link_to "Quay lại quản lý cây thuốc", ql_tvs_path %>
</div>

quanlysv/app/views/ql_tvs/show.html.erb
<div id="<%= dom_id @ql_tv %>">
 <section class="vh-100 gradient-custom">
  <div class="container py-5 h-100">
    <div class="row justify-content-center align-items-center h-100">
      <div class="col-12 col-lg-9 col-xl-7">
        <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
          <div class="card-body p-4 p-md-5">
          <p style="color: green"><%= notice %></p>
            <h3 class="mb-4 pb-2 pb-md-0 mb-md-5">Thông tin chi tiết cây thuốc: <label style="color:red"><%= @ql_tv.sv_name %></label> </h3>
              <div class="row">
                <div class="col-md-6 mb-4">

                  <div class="form-outline">
                    <input type="text" id="firstName" class="form-control form-control-lg" disabled value="<%= @ql_tv.sv_name %>">
                    <label class="form-label" for="firstName">Tên cây</label>
                  </div>

                </div>
                <div class="col-md-6 mb-4">

                  <div class="form-outline">
                    <input type="text" id="lastName" class="form-control form-control-lg" disabled value="<%= @ql_tv.sv_duoctinh %>" />
                    <label class="form-label" for="lastName">Dược tính</label>
                  </div>

                </div>
              </div>

               <div class="row">
                <div class="col-md-6 mb-4 pb-2">

                  <div class="form-outline datepicker w-100">
                    <input type="text" class="form-control form-control-lg" id="birthdayDate" disabled value="<%= @ql_tv.sv_dob.strftime('%d-%m-%Y') %>" />
                    <label for="birthdayDate" class="form-label">Ngày nhập</label>
                  </div>

                </div>
                <div class="col-md-6 mb-4 pb-2">

                  <div class="form-outline">
                    <input type="tel" id="phoneNumber" class="form-control form-control-lg" disabled value="<%= @ql_tv.sv_place %>" />
                    <label class="form-label" for="phoneNumber">Màu lá</label>
                  </div>

                </div>
              </div>

              <div class="row">
                <div class="col-md-6 mb-4 pb-2">

                  <div class="form-outline">
                    <input type="text" id="emailAddress" class="form-control form-control-lg" disabled value="<%= @ql_tv.sv_addr %>" />
                    <label class="form-label" for="emailAddress">Nơi trồng</label>
                  </div>

                </div>
                <div class="col-md-6 mb-4 pb-2">

                  <div class="form-outline">
                    <input type="tel" id="phoneNumber" class="form-control form-control-lg" disabled value="<%= @ql_tv.sv_class %>" />
                    <label class="form-label" for="phoneNumber">Đặc điểm</label>
                  </div>

                </div>
              </div>
              <div class="mt-4 pt-2">
              
                    <%= button_to "Xóa cây này",@ql_tv,class:"btn btn-danger",style:"float:left;display:inline-block",method: :delete %>
    
                    <%= link_to "Cập nhật thông tin", edit_ql_tv_path(@ql_tv), class:"btn btn-primary",style:"display:inline-block;margin-left:50px" %>
  
                    <%= link_to "Quay trờ lại quản lý cây thuốc", ql_tvs_path,class:"btn btn-secondary",style:"display:inline-block;float:right" %>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<div>
  <br>
  <br>



</div>

</div>

quanlysv/app/views/session/new.html.erb
<div class="login">
<h2 class="label_login">Đăng Nhập</h2>    
<%= form_for :session, url: login_path do |f| %>
  <!-- ID input -->
  <div class="form-outline mb-4">
  <br>
      <p style="color: red;"><%= notice %></p>
    <%= f.text_field :id, placeholder: "Nhập mã sinh viên", class: "form-control" %>
    <label class="form-label" for="form2Example1">Mã sinh viên</label>
  </div>

  <!-- Password input -->
  <div class="form-outline mb-4">
    <%= f.password_field :password, placeholder: "Nhập mật khẩu", class: "form-control" %>
    <label class="form-label" for="form2Example2">Mật khẩu</label>
  </div>

  <!-- 2 column grid layout for inline styling -->
  <div class="row mb-4">
    <div class="col d-flex justify-content-center">
      <!-- Checkbox -->
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="form2Example31" checked />
        <label class="form-check-label" for="form2Example31" style="padding-left:20px"> Remember me </label>
      </div>
    </div>

    <div class="col">
      <!-- Simple link -->
      <a href="#!">Forgot password?</a>
      
    </div>
  </div>

  <!-- Submit button -->
  <%= f.submit "Đăng nhập", class: "btn btn-info col-lg-12" %>

  <!-- Register buttons -->
  <div class="text-center">
    <a href="#!"><%= link_to "Đăng ký tài khoản mới" , new_ql_tv_path %>
</a></p>
  </div>
 <% end %>
</div>